<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="testMapsDemo"
    errors="0" failures="1" hostname="" id="" package="testMapsDemo" skipped="0"
    tests="1" time="0.000" timestamp="Fri, 02 Oct 2015 11:43:50 GMT">
  
    <testcase name="Demo test Address List title contains e" time="5.304" assertions="1">  <failure message="Timed out while waiting for element &lt;#myAddressList&gt; to be present for 1000 milliseconds.">    at Object.module.exports.Demo test Address List title contains e (C:\Users\cigdem.aytekin\devl\NightwatchTest\tests\testMapsDemo.js:17:14)
    at Module.call (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\lib\runner\module.js:60:34)
    at C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\lib\runner\testcase.js:96:29
    at _fulfilled (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\cigdem.aytekin\devl\NightwatchTest\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
